# Generated by Django 5.1.3 on 2024-12-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='post/photos')),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalon.brand')),
            ],
        ),
    ]
