# Generated by Django 5.1.3 on 2024-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0004_car_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='added',
            field=models.DateTimeField(default='2024-12-11 05:00:00'),
        ),
    ]
